### ISSUE TITLE
Javadoc button on Source Code page redirect to nothing (Error 404 Not Found)

### ISSUE THREAD

**Issue by kevinega** [Alieff/timAul#12]
this happened because the page that it redirect doesn't exist yet.

**Comment by haryoaw** [comment]
Fixed, 

Change the URL /timAul/InspireCrawler/doc2/index.html into /InspireCrawler/doc2/index.html

I will push it later.

**Comment by haryoaw** [comment]
https://github.com/Alieff/timAul/commit/83d4c385aee66ad27c07b5fe5d1d3282bb029b71 fixed here
