### ISSUE TITLE
Can't access the web

### ISSUE THREAD

**Issue by Alieff** [Alieff/timAul#14]
Hello :dancers: ,

After I pull the latest version of development branch i got this error when i try to access the landing page 
here is the image : ![unavailable to access](https://cloud.githubusercontent.com/assets/9797980/15090928/b203ae7e-1462-11e6-8091-3541858c45a0.png)

I also have tried to update, reinstall, self-update my composer, but none of them give me the expected result, 
here are the images : 
install 
![composer install](https://cloud.githubusercontent.com/assets/9797980/15090934/ef7a60b8-1462-11e6-9d84-20f065a351ed.png)
update
![composer update](https://cloud.githubusercontent.com/assets/9797980/15090936/f27460de-1462-11e6-96d8-d2209d74f39e.png)
self-update
![self-update then update](https://cloud.githubusercontent.com/assets/9797980/15090937/0395a936-1463-11e6-9b85-5e7b3eb8880c.png)

if you have solved it please let me know :+1:

**Comment by haryoaw** [comment]
Ez, you haven't installed the php mongodb  driver yet in your computer. Install it to solve it

Here's the reference :+1: http://php.net/manual/en/set.mongodb.php

**Comment by haryoaw** [comment]
Btw, I will close this issue. Feel free to open it if you find another problem.
