### ISSUE TITLE
Halaman Javadoc tidak Muncul

### ISSUE THREAD

**Issue by pflarasati** [Alieff/timAul#17]
![screen shot 2016-05-15 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/16837673/15272425/dba054fe-1aa1-11e6-985e-26c043fb3727.png)
Link Javadoc dari halaman Source Code mengarah ke halaman diatas

**Comment by Alieff** [comment]
hmm, path di OS @pflarasati gunain backslash "\" atau forwardslash "/" ? 
saya menggunakan forward slash "/" , dan bisa,

**Comment by haryoaw** [comment]
Gunakan "/", dah dicoba @pflarasati ?

**Comment by pflarasati** [comment]
Terima kasih atas jawabannya Alieff dan Haryo, ternyata saya lupa menambahkan folder yang berisi javadocnya. Case closed ya :)
