### ISSUE TITLE
Form on Setting Page for Crawler is not working

### ISSUE THREAD

**Issue by pflarasati** [Alieff/timAul#22]
Controller, Request and Form for Configuring Crawler Settings is made. But somehow after submitting the form, the value won't passed to controller. In other words, it passes empty values to controller. So it cannot be used to modify config.txt

Before Submitting Form
![screen shot 2016-05-18 at 11 00 40 pm](https://cloud.githubusercontent.com/assets/16837673/15365963/770163b4-1d4c-11e6-8b34-b5b7195be0fb.png)

After Submitting Form
![screen shot 2016-05-18 at 11 00 49 pm](https://cloud.githubusercontent.com/assets/16837673/15365990/911fdbd6-1d4c-11e6-800b-3370dbe23a1a.png)

**Comment by pflarasati** [comment]
This bug has been fixed and this features is ready to be used. The problem before was because i forgot to add name attribute on input tag for the form. Therefore the request cannot get the value from the input fields. After adding name attribute, and editing setting controller this form works fine!

`<div class="form-group {!! $errors->has('page_number') ? 'has-error' : '' !!}">
     <label for="page_number">Page Number</label>
     <input type="text" class="form-control" id="page_number" name="page_number" value= {!!$data['page_number']!!} >
     {!! $errors->first('page_number', '<p class="help-block">:message</p>') !!}
</div>`

Thank you, now I am closing this ticket because its already been fixed!

**Comment by haryoaw** [comment]
Ngasih bug sendiri... Nyelesain sendiri.. wkwkwk
