### ISSUE TITLE
Not-the-page it's supposed to be

### ISSUE THREAD

**Issue by aulch** [Alieff/timAul#7]
When I clicked the menu API in the navbar, it directed me to Term of Use page. It should be Documentation page which was supposed to be loaded.

**Comment by haryoaw** [comment]
Le me fix that

**Comment by haryoaw** [comment]
Solved, will be pushed

**Comment by haryoaw** [comment]
https://github.com/Alieff/timAul/commit/83d4c385aee66ad27c07b5fe5d1d3282bb029b71 fixed here
