### ISSUE TITLE
Positioning Button on Homepage and Footer

### ISSUE THREAD

**Issue by pflarasati** [Alieff/timAul#9]
Saat tampilannya diubah jadi mobile, positioning button dan footer keluar dari daerah yang seharusnya.

**Comment by pflarasati** [comment]
Halaman Aboutnya belum responsive dan menggunakan grid dari bootstrap, penggunaan warna dan font juga tidak seusai dengan yang ada di guideline.

**Comment by aulch** [comment]
Yap, untuk responsivitas pada image belum sempurna. Untuk penggunaan warna itu sudah dicoba disesuaikan dengan mockup, karena keterbatasan ilmu untuk mengetahui rgb dr warna-warna tersebut, jadinya manually pilih warna yang "sekiranya" sama seperti mockup.

**Comment by pflarasati** [comment]
Untuk pemilihan warna, bisa dilihat berdasarkan guideline yang sudah dibuat, dan coba cari converternya ke dalam bentuk rgb atau hex

**Comment by pflarasati** [comment]
Pewarnaan pada halaman ini sudah saya revisi, dan push ke branch-puti. Maka ticket akan saya tutup. Terima kasih
